# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backup.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='backup.proto',
  package='huawei.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x62\x61\x63kup.proto\x12\x0chuawei.proto\"\x99\x01\n\x0c\x42\x61\x63kupOption\x12-\n\x0b\x62\x61\x63kup_mode\x18\x01 \x01(\x0e\x32\x18.huawei.proto.BackupMode\x12\x31\n\nstore_mode\x18\x02 \x01(\x0e\x32\x1d.huawei.proto.BackupStoreMode\x12\x12\n\nchunk_size\x18\x03 \x01(\r\x12\x13\n\x0b\x62\x61\x63kup_path\x18\x04 \x01(\t\"[\n\rRestoreBlocks\x12\x10\n\x08vol_name\x18\x01 \x01(\t\x12\x13\n\x0b\x62\x61\x63kup_name\x18\x02 \x01(\t\x12\x10\n\x08\x62lock_no\x18\x03 \x03(\x04\x12\x11\n\tblock_obj\x18\x04 \x03(\t*?\n\nBackupMode\x12\x0f\n\x0b\x42\x41\x43KUP_FULL\x10\x00\x12\x0f\n\x0b\x42\x41\x43KUP_INCR\x10\x01\x12\x0f\n\x0b\x42\x41\x43KUP_DIFF\x10\x02*5\n\x0f\x42\x61\x63kupStoreMode\x12\x0f\n\x0b\x42\x41\x43KUP_FILE\x10\x00\x12\x11\n\rBACKPU_OBJECT\x10\x01*\x8b\x01\n\x0c\x42\x61\x63kupStatus\x12\x13\n\x0f\x42\x41\x43KUP_CREATING\x10\x00\x12\x12\n\x0e\x42\x41\x43KUP_CREATED\x10\x01\x12\x13\n\x0f\x42\x41\x43KUP_DELETING\x10\x02\x12\x12\n\x0e\x42\x41\x43KUP_DELETED\x10\x03\x12\x14\n\x10\x42\x41\x43KUP_RESTORING\x10\x04\x12\x13\n\x0f\x42\x41\x43KUP_RESTORED\x10\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_BACKUPMODE = _descriptor.EnumDescriptor(
  name='BackupMode',
  full_name='huawei.proto.BackupMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BACKUP_FULL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACKUP_INCR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACKUP_DIFF', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=279,
  serialized_end=342,
)
_sym_db.RegisterEnumDescriptor(_BACKUPMODE)

BackupMode = enum_type_wrapper.EnumTypeWrapper(_BACKUPMODE)
_BACKUPSTOREMODE = _descriptor.EnumDescriptor(
  name='BackupStoreMode',
  full_name='huawei.proto.BackupStoreMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BACKUP_FILE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACKPU_OBJECT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=344,
  serialized_end=397,
)
_sym_db.RegisterEnumDescriptor(_BACKUPSTOREMODE)

BackupStoreMode = enum_type_wrapper.EnumTypeWrapper(_BACKUPSTOREMODE)
_BACKUPSTATUS = _descriptor.EnumDescriptor(
  name='BackupStatus',
  full_name='huawei.proto.BackupStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BACKUP_CREATING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACKUP_CREATED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACKUP_DELETING', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACKUP_DELETED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACKUP_RESTORING', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACKUP_RESTORED', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=400,
  serialized_end=539,
)
_sym_db.RegisterEnumDescriptor(_BACKUPSTATUS)

BackupStatus = enum_type_wrapper.EnumTypeWrapper(_BACKUPSTATUS)
BACKUP_FULL = 0
BACKUP_INCR = 1
BACKUP_DIFF = 2
BACKUP_FILE = 0
BACKPU_OBJECT = 1
BACKUP_CREATING = 0
BACKUP_CREATED = 1
BACKUP_DELETING = 2
BACKUP_DELETED = 3
BACKUP_RESTORING = 4
BACKUP_RESTORED = 5



_BACKUPOPTION = _descriptor.Descriptor(
  name='BackupOption',
  full_name='huawei.proto.BackupOption',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='backup_mode', full_name='huawei.proto.BackupOption.backup_mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='store_mode', full_name='huawei.proto.BackupOption.store_mode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chunk_size', full_name='huawei.proto.BackupOption.chunk_size', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='backup_path', full_name='huawei.proto.BackupOption.backup_path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=184,
)


_RESTOREBLOCKS = _descriptor.Descriptor(
  name='RestoreBlocks',
  full_name='huawei.proto.RestoreBlocks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vol_name', full_name='huawei.proto.RestoreBlocks.vol_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='backup_name', full_name='huawei.proto.RestoreBlocks.backup_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='block_no', full_name='huawei.proto.RestoreBlocks.block_no', index=2,
      number=3, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='block_obj', full_name='huawei.proto.RestoreBlocks.block_obj', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=277,
)

_BACKUPOPTION.fields_by_name['backup_mode'].enum_type = _BACKUPMODE
_BACKUPOPTION.fields_by_name['store_mode'].enum_type = _BACKUPSTOREMODE
DESCRIPTOR.message_types_by_name['BackupOption'] = _BACKUPOPTION
DESCRIPTOR.message_types_by_name['RestoreBlocks'] = _RESTOREBLOCKS
DESCRIPTOR.enum_types_by_name['BackupMode'] = _BACKUPMODE
DESCRIPTOR.enum_types_by_name['BackupStoreMode'] = _BACKUPSTOREMODE
DESCRIPTOR.enum_types_by_name['BackupStatus'] = _BACKUPSTATUS

BackupOption = _reflection.GeneratedProtocolMessageType('BackupOption', (_message.Message,), dict(
  DESCRIPTOR = _BACKUPOPTION,
  __module__ = 'backup_pb2'
  # @@protoc_insertion_point(class_scope:huawei.proto.BackupOption)
  ))
_sym_db.RegisterMessage(BackupOption)

RestoreBlocks = _reflection.GeneratedProtocolMessageType('RestoreBlocks', (_message.Message,), dict(
  DESCRIPTOR = _RESTOREBLOCKS,
  __module__ = 'backup_pb2'
  # @@protoc_insertion_point(class_scope:huawei.proto.RestoreBlocks)
  ))
_sym_db.RegisterMessage(RestoreBlocks)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
